baseURL = "https://dpy.tips"
title = "discord.py Bot Tutorial"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]

#  menu items
[[menu.main]]
  name = "Docs"
  weight = 2
  url = "docs/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

# Everything below this are Site Params

[params]

  repo = "https://github.com/vcokltfre/tutorial"

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  enableDarkMode = true

  codeMaxLines = 20

  codeLineNumbers = true

  [params.source]
    name = "GitHub"
    url = "https://github.com/vcokltfre/tutorial"