baseURL = "https://vcokltfre.dev"
title = "discord.py Bot Tutorial"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]

#  menu items
[[menu.main]]
  name = "Tutorial"
  weight = 2
  url = "tutorial/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

# Everything below this are Site Params

[params]

  repo = "https://github.com/vcokltfre/tutorial"

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  enableDarkMode = true

  codeMaxLines = 30

  codeLineNumbers = true

  [params.source]
    name = "GitHub"
    url = "https://github.com/vcokltfre/tutorial"

  [params.logo]
    darkMode = "site/icon.svg"
    lightMode = "site/icon.svg"
